In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

In [14]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [15]:
laptops = pd.read_csv("flipkart_laptops.csv", encoding='latin1')
mobiles = pd.read_csv("flipkart_mobiles.csv", encoding='latin1')
tv = pd.read_csv("flipkart_tv.csv", encoding='latin1')
fridge = pd.read_csv("flipkart_refrigerator.csv", encoding='latin1')
watch = pd.read_csv("flipkart_smart_watch.csv", encoding='latin1')
wm = pd.read_csv("flipkart_washing_machine.csv", encoding='latin1')

In [16]:
laptops["category"] = "laptop"
mobiles["category"] = "mobile"
tv["category"] = "tv"
fridge["category"] = "refrigerator"
watch["category"] = "smart_watch"
wm["category"] = "washing_machine"

In [17]:
df = pd.concat([laptops, mobiles, tv, fridge, watch, wm], ignore_index=True)

In [18]:
df.shape

(2525, 9)

In [19]:
df.head()

,Name,Brand,Selling Price,MRP,Discount,Ratings,No_of_ratings,Details,category
0,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...,Lenovo,36990,60890,39% off,4.2,670 Ratings & 54 Reviews,['Intel Core i3 Processor (11th Gen)' '8 GB DD...,laptop
1,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...,Lenovo,37990,59390,36% off,4.2,3803 Ratings & 362 Reviews,['Intel Core i3 Processor (11th Gen)' '8 GB DD...,laptop
2,ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...,ASUS,32990,45990,28% off,4.3,8727 Ratings & 876 Reviews,['Intel Core i3 Processor (10th Gen)' '8 GB DD...,laptop
3,realme Book (Slim) Core i3 11th Gen - (8 GB/25...,realme,46990,54999,14% off,4.4,11894 Ratings & 1773 Reviews,['Stylish & Portable Thin and Light Laptop' '1...,laptop
4,DELL Inspiron Core i3 11th Gen - (8 GB/1 TB HD...,DELL,38990,61202,36% off,4.3,65 Ratings & 6 Reviews,['Processor: Intel i3-1115G4 (Base- 1.70 GHz &...,laptop

In [20]:
df.columns

Index(['Name', 'Brand', 'Selling Price', 'MRP', 'Discount', 'Ratings',
       'No_of_ratings', 'Details', 'category'],
      dtype='object')

In [21]:
df=df[['Name','Brand','category','Details','Selling Price','Ratings','No_of_ratings']]

In [24]:
df.isnull().sum()

Name             0
Brand            0
category         0
Details          0
Selling Price    0
Ratings          0
No_of_ratings    0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(3)

In [26]:
df=df.drop_duplicates().reset_index(drop=True)

In [27]:
df['combined']=df['Name']+df['Brand']+df['category']+df['Details']

In [28]:
df.head()

,Name,Brand,category,Details,Selling Price,Ratings,No_of_ratings,combined
0,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...,Lenovo,laptop,['Intel Core i3 Processor (11th Gen)' '8 GB DD...,36990,4.2,670 Ratings & 54 Reviews,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...
1,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...,Lenovo,laptop,['Intel Core i3 Processor (11th Gen)' '8 GB DD...,37990,4.2,3803 Ratings & 362 Reviews,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...
2,ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...,ASUS,laptop,['Intel Core i3 Processor (10th Gen)' '8 GB DD...,32990,4.3,8727 Ratings & 876 Reviews,ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...
3,realme Book (Slim) Core i3 11th Gen - (8 GB/25...,realme,laptop,['Stylish & Portable Thin and Light Laptop' '1...,46990,4.4,11894 Ratings & 1773 Reviews,realme Book (Slim) Core i3 11th Gen - (8 GB/25...
4,DELL Inspiron Core i3 11th Gen - (8 GB/1 TB HD...,DELL,laptop,['Processor: Intel i3-1115G4 (Base- 1.70 GHz &...,38990,4.3,65 Ratings & 6 Reviews,DELL Inspiron Core i3 11th Gen - (8 GB/1 TB HD...

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
stop_words=set(nltk.corpus.stopwords.words('english'))

In [32]:
def preprocess(text):
    text=text.lower()
    tokens=nltk.word_tokenize(text)
    tokens=[token for token in tokens if token.isalpha()]
    tokens=[token for token in tokens if token not in stop_words]
    lemmatizer=nltk.stem.WordNetLemmatizer()
    tokens=[lemmatizer.lemmatize(token) for token in tokens]
    preprocessed_text=' '.join(tokens)
    return preprocessed_text

In [33]:
df['combined']=df['combined'].apply(preprocess)

In [34]:
df['combined'][0]

'lenovo ideapad core gen gb home thin light laptoplenovolaptop core processor gen gb ram bit window operating system gb ssd cm inch display home student year'

In [35]:
df.head()

,Name,Brand,category,Details,Selling Price,Ratings,No_of_ratings,combined
0,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...,Lenovo,laptop,['Intel Core i3 Processor (11th Gen)' '8 GB DD...,36990,4.2,670 Ratings & 54 Reviews,lenovo ideapad core gen gb home thin light lap...
1,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...,Lenovo,laptop,['Intel Core i3 Processor (11th Gen)' '8 GB DD...,37990,4.2,3803 Ratings & 362 Reviews,lenovo ideapad core gen gb home lenovolaptop c...
2,ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...,ASUS,laptop,['Intel Core i3 Processor (10th Gen)' '8 GB DD...,32990,4.3,8727 Ratings & 876 Reviews,asus vivobook core gen gb home asuslaptop core...
3,realme Book (Slim) Core i3 11th Gen - (8 GB/25...,realme,laptop,['Stylish & Portable Thin and Light Laptop' '1...,46990,4.4,11894 Ratings & 1773 Reviews,realme book slim core gen gb home thin light l...
4,DELL Inspiron Core i3 11th Gen - (8 GB/1 TB HD...,DELL,laptop,['Processor: Intel i3-1115G4 (Base- 1.70 GHz &...,38990,4.3,65 Ratings & 6 Reviews,dell inspiron core gen tb gb home thin ligh de...

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tfidf=TfidfVectorizer(max_features=5000,ngram_range=(1,2),stop_words='english')

In [38]:
tfidf_matrix=tfidf.fit_transform(df['combined'])

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [42]:
def recommand(product,n=10):
    product_index=df[df['Name']==product].index[0]
    similarity_scores=cosine_similarity(tfidf_matrix[product_index],tfidf_matrix).flatten()
    # Get indices of products sorted by similarity scores in descending order
    recommended_products_indices=similarity_scores.argsort()[::-1]

    # Exclude the input product itself from recommendations
    recommended_products_indices=recommended_products_indices[1:]

    # Get the top n recommended product names
    recommended_products = df['Name'].iloc[recommended_products_indices[:n]].tolist()

    return recommended_products

In [46]:
sample_laptop_name = df[df['category'] == 'laptop']['Name'].iloc[0]
print(f"Using sample laptop name: {sample_laptop_name}")
recommand(sample_laptop_name)

Using sample laptop name: Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) 14ITL05 Thin and Light Laptop

['Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) 15ITL05 Thin and Light Laptop',
 'Lenovo IdeaPad 3 Core i5 12th Gen - (16 GB/512 GB SSD/Windows 11 Home) 15IAU7 Thin and Light Laptop',
 'Lenovo IdeaPad Core i3 10th Gen - (4 GB/256 GB SSD/Windows 11 Home) 15IIL05 Thin and Light Laptop',
 'Lenovo IdeaPad 3 Core i5 12th Gen - (8 GB/512 GB SSD/Windows 11 Home) 15IAU7 Thin and Light Laptop',
 'Lenovo IdeaPad 3 Core i3 10th Gen - (8 GB/256 GB SSD/Windows 11 Home) 15IML05 Thin and Light Laptop',
 'Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 GB SSD/Windows 10 Home) 15ITL6 Thin and Light Laptop',
 'Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) 82H801L7IN | 82H802FJIN | 82H802...',
 'Lenovo Ideapad S145 Core i3 10th Gen - (4 GB/256 GB SSD/Windows 10 Home) S145-15IIL Thin and Light Lap...',
 'Lenovo Core i3 11th Gen - (4 GB/256 GB SSD/Windows 10 Home) V15 ITL G2 Thin and Light Laptop',
 'Lenovo IdeaPad 3 Core i3 10th Gen - (8 GB/1 TB HDD/Windows 10 Home) 15IML05 Thin and Light Laptop']

In [48]:
import pickle

In [49]:
with open('recommendation_system.pkl','wb') as file:
    pickle.dump({'df':df,'tfidf':tfidf,'tfidf_matrix':tfidf_matrix},file)